name: Build and Publish image

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GOOGLE_CREDS: ${{ secrets.GCP_CREDENTIALS }}
  GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      - name: Build
        run: |
          docker build \
            -f dbt_worker.Dockerfile \
            -t us-central1-docker.pkg.dev/terraform-poc-417803/dbt-core-worker/dbtcoreworker:latest \
            --build-arg "github_token=$GITHUB_TOKEN" \
            --build-arg "google_credentials=$GOOGLE_CREDS" .
          .
      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |
          docker push us-central1-docker.pkg.dev/terraform-poc-417803/dbt-core-worker/dbtcoreworker:latest
