name: Build and Publish image

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GOOGLE_CREDS: ${{ secrets.GCP_CREDENTIALS }}
  GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      # Auth into docker
      - name: "Docker auth"
        run: |-
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

      - name: Use the JSON secret
        run: |
          # Access the secret and store it in a file
          echo "${{ secrets.GCP_CREDENTIALS }}" > google_creds_key.json

      # Build the Docker image
      - name: Build
        run: |
          docker build \
            -f dbt_worker.Dockerfile \
            -t us-central1-docker.pkg.dev/terraform-poc-417803/dbt-core-worker/dbtcoreworker:latest \
            --build-arg "google_credentials=./google_creds_key.json" .

      # Push the Docker image to Google Artifact Registry
      - name: Publish
        run: |
          docker push us-central1-docker.pkg.dev/terraform-poc-417803/dbt-core-worker/dbtcoreworker
